### ISSUE TITLE
error "there should be a subclass of BaseModel with class name that...."

### ISSUE THREAD

**Issue by Dannynis** [Tinglok/CVC#1]
Hey, thank you for the implementation !!
Im getting the error on line 45 in __init__.py in models, when starting cvc train as described in readme
In models.cvc_model.py, there should be a subclass of BaseModel with class name that matches cvcmodel in lowercase.
also, could you please specify the parallelwavegan config you used ? the one in the parameters is hard coded to your folder ?

**Comment by Tinglok** [comment]
Hi Dannynis, thanks for your interest and feedback!
We still busy cleaning up the codes right now, problems will be solved in the next version. :)

**Comment by Tinglok** [comment]
Hi @Dannynis,
We already fix the bugs you mentioned, please see the latest README for pre-trained parallelwavegan. 
Feel free to reach out if you have any other questions!

**Comment by Ron-carry** [comment]
Hello, have you solved your problem? Could you guide me to a solution? 
Thank you very much!
