### ISSUE TITLE
About converted samples.

### ISSUE THREAD

**Issue by 17011775** [Tinglok/CVC#4]
Hi, I preprared dataset for One-to-One(p226 -> p225)VC experiment (p226 in trainA, p225 in trainB).
After training, I ran the test code, but the converted samples is strange. 

sample : https://drive.google.com/file/d/1AfZlx3tTxWZyegFsrcrbKqPNsebs4ysm/view

The first few seconds are silence and then a voice is heard momentarily at the end.
I wonder why this is happening and what I should do to get a normal converted sample.
Thanks!

**Comment by Tinglok** [comment]
Hey, I can't open the link because I don't have permission.
But judging from what you said, I think you could try other checkpoints to see if it works better since the latest checkpoint doesn't mean it's the best.

    python test.py --epoch xxx --dataroot ./datasets/voice --validation_A_dir ./datasets/voice/trainA --output_A_dir ./checkpoints/CVC/converted_sound

If not, the problem may be in the vocoder or your running environment.

**Comment by Tinglok** [comment]
Besides, I strongly suggest you should write a code to exclude the utterance less than 2s because contrastive-based methods suffer when it comes to zero-padding.
