### ISSUE TITLE
if I use my own dataset, does that mean I have to train ParallelWaveGAN first?

### ISSUE THREAD

**Issue by chikiuso** [Tinglok/CVC#6]
Hi, I see there is a pretrained checkpoints of ParallelWaveGAN which I have to download first before training, does that mean I have to train ParallelWaveGAN first if I use my old dataset? thanks.

**Comment by Tinglok** [comment]
Hi @chikiuso,
Yes, you were right. The neural vocoder does not have the speaker-independent ability so far. 
If you want to convert your own dataset, please see this [URL](https://github.com/kan-bayashi/ParallelWaveGAN) for training ParallelWaveGAN from scratch.

**Comment by chikiuso** [comment]
Hi @Tinglok , thanks for your reply. ParallelWaveGAN seems not a non-parallel model, does that mean I have to train it with a parallel voice dataset?

**Comment by Tinglok** [comment]
Hi @chikiuso, I am not sure about the training details of the ParallelWaveGAN vocoder, but I think you are right.
